Distributed LLM Inference Gateway: llmgateway::gossip::UdpTransport Class Reference
llmgateway::gossip::UdpTransport Class Reference
#include <udp_transport.h>
Public Member Functions
UdpTransport (uint16_t bind_port)
~UdpTransport ()
UdpTransport (const UdpTransport &)=delete
Non-copyable, non-movable (owns a socket)
UdpTransport & operator= (const UdpTransport &)=delete
bool Send (const Address &dest, const GossipMessage &message)
Send a GossipMessage to the given address. Returns true on success.
std::optional< std::pair< GossipMessage, Address > > Receive (int timeout_ms)
Receive a GossipMessage with a timeout. Returns nullopt on timeout or error.
uint16_t port () const
Private Attributes
int sock_fd_ = -1
uint16_t port_
Detailed Description
UdpTransport: thin UDP wrapper used by the SWIM gossip layer.
Owns a single bound UDP socket. Messages are GossipMessage protobufs serialized to bytes; datagrams are assumed to fit in a single packet (SWIM gossip messages with piggyback are well under the typical 64KB IP datagram limit at the cluster sizes this project targets).
Thread-safety: Send() and Receive() may be called concurrently from different threads — the OS socket API is thread-safe for this pattern, and the SWIM protocol uses exactly one sender thread and one receiver thread. Copying and moving are disabled because the socket fd is owned.
Lifetime: the socket is created in the constructor and closed in the destructor. Construction throws std::runtime_error if bind() fails
(e.g., port already in use).
Definition at line 53 of file udp_transport.h.
Constructor & Destructor Documentation
UdpTransport() [1/2]
llmgateway::gossip::UdpTransport::UdpTransport (uint16_t bind_port) explicit
Allow address reuse (useful when restarting quickly)
Definition at line 28 of file udp_transport.cpp.
References port_, and sock_fd_.
Referenced by operator=(), and UdpTransport().
~UdpTransport()
llmgateway::gossip::UdpTransport::~UdpTransport ()
Definition at line 52 of file udp_transport.cpp.
References sock_fd_.
UdpTransport() [2/2]
llmgateway::gossip::UdpTransport::UdpTransport (const UdpTransport &) delete
Non-copyable, non-movable (owns a socket)
References UdpTransport().
Member Function Documentation
operator=()
UdpTransport & llmgateway::gossip::UdpTransport::operator= (const UdpTransport &) delete
References UdpTransport().
Send()
bool llmgateway::gossip::UdpTransport::Send (const Address & dest, const GossipMessage & message)
Send a GossipMessage to the given address. Returns true on success.
Resolve hostname
Definition at line 58 of file udp_transport.cpp.
References llmgateway::gossip::Address::host, llmgateway::gossip::kMaxDatagram, llmgateway::gossip::Address::port, sock_fd_, and llmgateway::gossip::Address::ToString().
Receive()
std::optional< std::pair< GossipMessage, Address > > llmgateway::gossip::UdpTransport::Receive (int timeout_ms)
Receive a GossipMessage with a timeout. Returns nullopt on timeout or error.
Timeout or error
Extract sender address
Definition at line 95 of file udp_transport.cpp.
References llmgateway::gossip::kMaxDatagram, and sock_fd_.
port()
uint16_t llmgateway::gossip::UdpTransport::port () const inline
Definition at line 68 of file udp_transport.h.
References port_.
Member Data Documentation
sock_fd_
int llmgateway::gossip::UdpTransport::sock_fd_ = -1 private
Definition at line 71 of file udp_transport.h.
Referenced by Receive(), Send(), UdpTransport(), and ~UdpTransport().
port_
uint16_t llmgateway::gossip::UdpTransport::port_ private
Definition at line 72 of file udp_transport.h.
Referenced by port(), and UdpTransport().
The documentation for this class was generated from the following files:
src/gossip/udp_transport.h
src/gossip/udp_transport.cpp