Distributed LLM Inference Gateway: llmgateway::InferenceClient Class Reference
llmgateway::InferenceClient Class Reference
#include <client.h>
Public Member Functions
InferenceClient (const std::string &target_address)
InferResult Infer (const std::string &client_id, const std::string &prompt, int max_tokens, bool hedge=false)
Blocking inference: sends request, collects all streamed tokens, returns result.
InferResult InferWithCallback (const std::string &client_id, const std::string &prompt, int max_tokens, TokenCallback on_token)
Blocking inference with per-token callback (for mid-stream test control).
InferResult GenerateDirect (const std::string &request_id, const std::string &prompt, int max_tokens, int tokens_already_generated=0)
Direct replica call (for testing without gateway).
Static Public Member Functions
static std::vector< InferResult > InferConcurrent (const std::string &target_address, int count, const std::string &client_id, const std::string &prompt_prefix, int max_tokens, bool hedge=false)
Fire N concurrent inference requests and collect all results.
Private Attributes
std::unique_ptr< InferenceGateway::Stub > stub_
std::unique_ptr< LLMReplica::Stub > replica_stub_
Detailed Description
InferenceClient: blocking gRPC client for the LLM inference service.
Typical usage is against the gateway (which load-balances across replicas), but the client also exposes GenerateDirect() for bypass mode that talks to a replica directly — used by tests to verify per-replica behavior without the gateway in the loop.
All Infer* methods block the caller's thread until the stream completes, fails, or is cancelled. Each InferenceClient owns a gRPC channel to its target_address; channels are thread-safe and may be reused across sequential calls, but concurrent calls on the same InferenceClient are
not supported (use InferConcurrent for parallelism instead).
Definition at line 54 of file client.h.
Constructor & Destructor Documentation
InferenceClient()
llmgateway::InferenceClient::InferenceClient (const std::string & target_address) explicit
Definition at line 8 of file client.cpp.
References replica_stub_, and stub_.
Referenced by InferConcurrent().
Member Function Documentation
Infer()
InferResult llmgateway::InferenceClient::Infer (const std::string & client_id, const std::string & prompt, int max_tokens, bool hedge = false)
Blocking inference: sends request, collects all streamed tokens, returns result.
Definition at line 15 of file client.cpp.
References llmgateway::InferResult::error_message, llmgateway::InferResult::replica_ids, stub_, llmgateway::InferResult::success, and llmgateway::InferResult::tokens.
Referenced by InferConcurrent(), and main().
InferWithCallback()
InferResult llmgateway::InferenceClient::InferWithCallback (const std::string & client_id, const std::string & prompt, int max_tokens, TokenCallback on_token)
Blocking inference with per-token callback (for mid-stream test control).
The callback is invoked for each token; returning false cancels the stream.
Invoke callback; if it returns false, cancel the stream.
Definition at line 49 of file client.cpp.
References llmgateway::InferResult::error_message, llmgateway::InferResult::replica_ids, stub_, llmgateway::InferResult::success, and llmgateway::InferResult::tokens.
GenerateDirect()
InferResult llmgateway::InferenceClient::GenerateDirect (const std::string & request_id, const std::string & prompt, int max_tokens, int tokens_already_generated = 0)
Direct replica call (for testing without gateway).
Definition at line 91 of file client.cpp.
References llmgateway::InferResult::error_message, replica_stub_, llmgateway::InferResult::success, and llmgateway::InferResult::tokens.
Referenced by main().
InferConcurrent()
std::vector< InferResult > llmgateway::InferenceClient::InferConcurrent (const std::string & target_address, int count, const std::string & client_id, const std::string & prompt_prefix, int max_tokens, bool hedge = false) static
Fire N concurrent inference requests and collect all results.
Each request gets a unique prompt (prompt_prefix + "_" + index). Returns results in the same order as the requests were issued.
Each thread creates its own client (own gRPC channel).
Definition at line 120 of file client.cpp.
References Infer(), and InferenceClient().
Member Data Documentation
stub_
std::unique_ptr<InferenceGateway::Stub> llmgateway::InferenceClient::stub_ private
Definition at line 82 of file client.h.
Referenced by Infer(), InferenceClient(), and InferWithCallback().
replica_stub_
std::unique_ptr<LLMReplica::Stub> llmgateway::InferenceClient::replica_stub_ private
Definition at line 83 of file client.h.
Referenced by GenerateDirect(), and InferenceClient().
The documentation for this class was generated from the following files:
src/client/client.h
src/client/client.cpp