Distributed LLM Inference Gateway: llmgateway::RollingUpdater Class Reference
llmgateway::RollingUpdater Class Reference
#include <rolling_updater.h>
Public Types
using StopCallback = std::function<void(const std::string& replica_id)>
Callbacks provided by the caller to control replica lifecycle.
using RestartCallback
Public Member Functions
RollingUpdater (ReplicaRegistry &registry, LoadBalancer &lb)
bool Update (const std::vector< std::string > &replica_ids, const std::string &new_version, StopCallback stop_fn, RestartCallback restart_fn, int drain_timeout_ms=30000, int rejoin_timeout_ms=10000)
Perform a rolling update: drain, stop, restart each replica in sequence.
bool DrainReplica (const std::string &replica_id, int timeout_ms=30000)
Drain a single replica: mark draining in registry + send Drain RPC.
bool WaitForRejoin (const std::string &replica_id, int timeout_ms=10000)
Wait for a replica to appear as ALIVE in the registry.
Private Attributes
ReplicaRegistry & registry_
LoadBalancer & lb_
Detailed Description
RollingUpdater: orchestrates zero-downtime rolling updates of replicas.
A rolling update replaces each replica one at a time with a new version while maintaining service availability. For each replica, the sequence is:
DRAIN: Mark the replica as draining in the gateway's registry (no new requests routed to it) and send a Drain RPC to the replica so it stops accepting new Generate calls and waits for in-flight requests to complete.
STOP: Invoke the stop callback (which kills the replica process or stops its gRPC server + gossip). The replica leaves the gossip network (detected as DEAD by peers, or via graceful leave if supported).
RESTART: Invoke the restart callback (which starts a new replica instance with the new model version on the same ports). The new replica joins the gossip network and is discovered by the gateway.
WAIT: Wait until the gateway sees the restarted replica as ALIVE and the hash ring is rebuilt.
During each drain phase, the remaining replicas absorb the traffic. The gateway's backpressure queue handles any temporary capacity reduction.
Usage (from test harness or admin tool): RollingUpdater updater(registry, lb); updater.Update({"r1", "r2", "r3"}, "v2", [](const string& id) { /* stop replica ‍/ }, [](const string& id, const string& version) { / restart replica *‍/ }
);
Definition at line 53 of file rolling_updater.h.
Member Typedef Documentation
StopCallback
using llmgateway::RollingUpdater::StopCallback = std::function<void(const std::string& replica_id)>
Callbacks provided by the caller to control replica lifecycle.
StopCallback: called to stop a drained replica (kill process, stop gRPC+gossip). RestartCallback: called to start a new replica with the given model version.
Definition at line 60 of file rolling_updater.h.
RestartCallback
using llmgateway::RollingUpdater::RestartCallback
Initial value:
 std::function<void(const std::string& replica_id,
                                               const std::string& new_version)>
Definition at line 61 of file rolling_updater.h.
Constructor & Destructor Documentation
RollingUpdater()
llmgateway::RollingUpdater::RollingUpdater (ReplicaRegistry & registry, LoadBalancer & lb)
Definition at line 16 of file rolling_updater.cpp.
References lb_, and registry_.
Member Function Documentation
Update()
bool llmgateway::RollingUpdater::Update (const std::vector< std::string > & replica_ids, const std::string & new_version, StopCallback stop_fn, RestartCallback restart_fn, int drain_timeout_ms = 30000, int rejoin_timeout_ms = 10000)
Perform a rolling update: drain, stop, restart each replica in sequence.
Returns true if all replicas were updated successfully.
Step 1: Drain — stop new requests, wait for in-flight to complete.
Un-drain so routing resumes to this replica.
Step 2: Stop — kill the replica process / stop gRPC + gossip.
Step 3: Restart — start a new instance with the new version.
Clear the draining flag and rebuild the ring so the restarted replica starts receiving traffic as soon as gossip marks it ALIVE. draining is a gateway-side flag that UpdateFromGossip does not touch, so we must explicitly reset it here after restart.
Step 4: Wait for the restarted replica to rejoin via gossip.
Continue anyway — the replica may rejoin later via gossip.
Definition at line 19 of file rolling_updater.cpp.
References DrainReplica(), lb_, LOG_ERROR, LOG_INFO, LOG_WARN, registry_, and WaitForRejoin().
DrainReplica()
bool llmgateway::RollingUpdater::DrainReplica (const std::string & replica_id, int timeout_ms = 30000)
Drain a single replica: mark draining in registry + send Drain RPC.
Returns true if the drain completed (all in-flight requests finished).
DrainReplica: mark the replica as draining and send a Drain RPC.
Two-step drain:
Mark draining in the gateway's registry so the load balancer stops routing new requests to this replica.
Send a Drain RPC to the replica itself so it rejects any new Generate calls and waits for in-flight requests to complete.
The Drain RPC is a blocking call — it returns only when all in-flight requests on the replica have finished. This guarantees that after DrainReplica returns, it's safe to stop the replica without dropping any requests.
If the Drain RPC fails (e.g., replica already crashed), we still consider the drain successful — there are no in-flight requests if
the replica is dead.
Step 1: Mark draining in the gateway registry.
Step 2: Send Drain RPC to the replica.
Set a deadline for the Drain RPC.
Drain RPC failed (replica may have crashed). That's OK — no in-flight requests if the replica is dead.
Definition at line 87 of file rolling_updater.cpp.
References lb_, LOG_INFO, LOG_WARN, and registry_.
Referenced by Update().
WaitForRejoin()
bool llmgateway::RollingUpdater::WaitForRejoin (const std::string & replica_id, int timeout_ms = 10000)
Wait for a replica to appear as ALIVE in the registry.
WaitForRejoin: poll the registry until the replica appears as ALIVE.
After a restart, the replica needs time to:
Start its gRPC server
Start its SWIM gossip protocol
Be discovered by the gateway's gossip subscriber
Have its state updated in the registry
Be added back to the hash ring
We poll every 200ms until the replica is ALIVE or the timeout expires.
Definition at line 144 of file rolling_updater.cpp.
References LOG_INFO, and registry_.
Referenced by Update().
Member Data Documentation
registry_
ReplicaRegistry& llmgateway::RollingUpdater::registry_ private
Definition at line 81 of file rolling_updater.h.
Referenced by DrainReplica(), RollingUpdater(), Update(), and WaitForRejoin().
lb_
LoadBalancer& llmgateway::RollingUpdater::lb_ private
Definition at line 82 of file rolling_updater.h.
Referenced by DrainReplica(), RollingUpdater(), and Update().
The documentation for this class was generated from the following files:
src/gateway/rolling_updater.h
src/gateway/rolling_updater.cpp