Distributed LLM Inference Gateway: llmgateway::GatewayServer Class Reference
llmgateway::GatewayServer Class Reference final
#include <gateway_server.h>
Public Member Functions
GatewayServer (int port, ReplicaRegistry &registry, LoadBalancer &lb, CircuitBreakerManager &cb_manager, RequestQueue &queue)
void Start ()
void Stop ()
int port () const
Private Member Functions
grpc::Status Infer (grpc::ServerContext *context, const InferRequest *request, grpc::ServerWriter< InferResponse > *writer) override
gRPC service handler: proxy streaming inference request to a replica.
grpc::Status InferHedged (grpc::ServerContext *context, const InferRequest *request, grpc::ServerWriter< InferResponse > *writer)
Handle a hedged request: send to 2 replicas simultaneously, stream from whichever produces the first token faster, cancel the slower one.
int StreamFromReplica (const std::string &replica_id, const std::string &grpc_address, const std::string &prompt, int max_tokens, int tokens_already_generated, grpc::ServerWriter< InferResponse > *writer, grpc::ServerContext *client_context)
Forward a Generate request to a specific replica and stream tokens back.
Private Attributes
int port_
ReplicaRegistry & registry_
LoadBalancer & lb_
CircuitBreakerManager & cb_manager_
RequestQueue & queue_
std::unique_ptr< grpc::Server > server_
Detailed Description
GatewayServer: the client-facing gRPC endpoint for inference requests.
Role – streaming reverse proxy: The gateway does not run any model itself. It accepts a client's InferRequest (prompt + max_tokens), selects a backend replica via the LoadBalancer, opens a server-streaming Generate RPC to that replica, and forwards each generated token back to the client as an InferResponse. From the client's perspective, the gateway is a single stable endpoint; the actual replica serving the request is transparent.
Mid-stream failover (DR4): If the backend replica fails or disconnects during streaming, the gateway does NOT return an error immediately. Instead, it selects a new replica via the load balancer and continues the stream from where it left off (using tokens_already_generated to tell the new replica how many tokens were already produced). The client sees a seamless token stream, possibly from multiple replicas. Up to max_retries failover attempts are made before giving up.
Integration with other components:
ReplicaRegistry: provides the set of known replicas and their state.
LoadBalancer: selects which replica to route each request to.
CircuitBreakerManager: gates requests to replicas that are returning
errors (application-level health, complementing gossip-level health).
Definition at line 47 of file gateway_server.h.
Constructor & Destructor Documentation
GatewayServer()
llmgateway::GatewayServer::GatewayServer (int port, ReplicaRegistry & registry, LoadBalancer & lb, CircuitBreakerManager & cb_manager, RequestQueue & queue)
Definition at line 12 of file gateway_server.cpp.
References cb_manager_, lb_, port(), port_, queue_, and registry_.
Member Function Documentation
Start()
void llmgateway::GatewayServer::Start ()
Definition at line 18 of file gateway_server.cpp.
References LOG_INFO, port_, and server_.
Referenced by main().
Stop()
void llmgateway::GatewayServer::Stop ()
Definition at line 29 of file gateway_server.cpp.
References LOG_INFO, and server_.
port()
int llmgateway::GatewayServer::port () const inline
Definition at line 55 of file gateway_server.h.
References port_.
Referenced by GatewayServer().
Infer()
grpc::Status llmgateway::GatewayServer::Infer (grpc::ServerContext * context, const InferRequest * request, grpc::ServerWriter< InferResponse > * writer) override private
gRPC service handler: proxy streaming inference request to a replica.
Implements the mid-stream failover retry loop.
Infer: the main request handler. This is the hot path for every client inference call and implements the mid-stream failover strategy.
Retry loop design: The loop runs up to max_retries times. Each iteration:
Check if the client cancelled (e.g., timeout, user abort).
Ask the LoadBalancer for a replica, passing an exclude set of replicas already known to be unusable for this request.
Check the circuit breaker. If the selected replica's circuit is OPEN, add it to the exclude set so the next iteration picks a different replica.
Increment the active-request counter (for load-balancer awareness), then stream tokens from the replica.
On success (streamed >= 0): accumulate tokens_sent, record a circuit-breaker success. If all tokens are delivered, return OK.
On replica failure (streamed == -1): record a circuit-breaker failure, add the replica to the exclude set, and retry. tokens_sent is NOT incremented, so the next replica picks up from where we left off via tokens_already_generated.
The exclude set is the key to robust retries: consistent-hashing selection is otherwise deterministic for a given prompt, so without exclusions the retry loop would keep picking the same broken replica every iteration.
Partial delivery: if some tokens were sent before all retries exhausted, return OK rather than an error. The client already received partial output on the stream, so an error status would be confusing. The client can detect incompleteness by checking whether is_final was ever true.
RESOURCE_EXHAUSTED: returned when no replica has capacity at all (before
any retry). This signals the client to back off or queue locally.
Dispatch to hedged path if requested and there are at least 2 replicas.
Fall through to normal path if not enough replicas for hedging.
Replicas to skip on subsequent retries for this request: circuits that tripped OPEN or streams that just failed. Consistent-hashing selection is deterministic for a given prompt, so without this set the retry loop would keep picking the same broken replica.
No replica has capacity — wait in the backpressure queue. The calling thread blocks until NotifyCapacityAvailable() is called (when another request finishes) or the timeout expires.
Retry selection after being woken.
Still no capacity (e.g., replica died while we were queued).
Circuit breaker check: if the replica is in OPEN state, skip it for the remainder of this request and let the LB pick another.
Track this in-flight request so the load balancer accounts for it.
Notify the backpressure queue that a slot has freed up. This wakes the next FIFO-waiting request thread (if any).
streamed == -1 signals a replica-side gRPC error. Record the failure so the circuit breaker can track the error rate and potentially open the circuit for this replica. Also exclude it from this request's retry set so we pick a different replica.
Partial stream (streamed > 0 but < remaining): the replica ended early. Don't retry the same replica — move on.
Partial delivery: some tokens were already written to the stream. Returning an error here would be misleading since the client already received data. Return OK and let the client detect incompleteness via the absence of is_final=true.
Definition at line 69 of file gateway_server.cpp.
References cb_manager_, InferHedged(), lb_, LOG_WARN, queue_, registry_, and StreamFromReplica().
InferHedged()
grpc::Status llmgateway::GatewayServer::InferHedged (grpc::ServerContext * context, const InferRequest * request, grpc::ServerWriter< InferResponse > * writer) private
Handle a hedged request: send to 2 replicas simultaneously, stream from whichever produces the first token faster, cancel the slower one.
InferHedged: speculative execution — race two replicas.
Strategy (inspired by Google's "The Tail at Scale"):
Select two different replicas via the load balancer.
Open Generate streams to both simultaneously (in separate threads).
Whichever replica produces its first token faster becomes the "winner."
Stream all remaining tokens from the winner to the client.
Cancel the loser's stream to free its capacity.
This reduces tail latency at the cost of extra replica utilization. The winner is determined by first-token latency (time to first Read()), not by which thread starts first. Both threads read one token, then signal via a shared promise. The main thread picks the winner and
continues streaming from it.
Select two different replicas.
For the second replica, we need a different one. Temporarily increment the first replica's active count so the LB deprioritizes it.
Only one replica available — fall through to non-hedged path. Re-select since we decremented.
Shared state for the race: each thread reads one token, then signals.
Promise: first thread to read a token sets it.
Lambda to open a stream and read the first token.
Read first token.
Try to be the winner.
The race threads capture prompt and max_tokens by reference from this stack frame, so both must be joined before InferHedged returns. The RAII guards enforce this on every exit path including exceptions; the explicit join() calls below handle the normal path.
Wait for the winner (with timeout).
Wait for both threads to finish their first-token read.
Neither replica produced a token.
Cancel the loser's stream.
Stream the winner's first token to the client.
Continue streaming remaining tokens from the winner.
Definition at line 193 of file gateway_server.cpp.
References cb_manager_, lb_, LOG_INFO, queue_, registry_, and StreamFromReplica().
Referenced by Infer().
StreamFromReplica()
int llmgateway::GatewayServer::StreamFromReplica (const std::string & replica_id, const std::string & grpc_address, const std::string & prompt, int max_tokens, int tokens_already_generated, grpc::ServerWriter< InferResponse > * writer, grpc::ServerContext * client_context) private
Forward a Generate request to a specific replica and stream tokens back.
Returns: >= 0 : number of tokens successfully streamed to the client. -1 : the replica stream failed (gRPC error). The caller should record a circuit breaker failure and retry with another replica. The -1 sentinel distinguishes "replica error" from "zero tokens streamed successfully", which matters for the retry/failover decision.
StreamFromReplica: the core streaming proxy logic.
Flow:
Create a gRPC channel+stub to the replica (one per call; channels are lightweight and cached internally by gRPC's channel pool).
Build a GenerateRequest with the original prompt, max_tokens, and tokens_already_generated. The replica uses tokens_already_generated to skip tokens that were already sent to the client by a previous replica (mid-stream failover).
Open a server-streaming RPC (Generate) and read tokens in a loop.
For each token: check if the client cancelled, then forward the token as an InferResponse on the client-facing stream. If the client disconnected (Write returns false), cancel the replica stream to avoid wasting GPU cycles.
After the Read loop ends, call Finish() to get the final gRPC status from the replica.
Return value convention: >= 0 : number of tokens successfully forwarded to the client. -1 : replica-side error (the gRPC stream terminated with a non-OK status). The caller (Infer) uses -1 to distinguish "zero tokens streamed successfully" from "stream failed before any token". This distinction drives the circuit-breaker recording:
-1 triggers RecordFailure; 0 does not.
Early exit if the downstream client has gone away.
Translate the replica's GenerateResponse into the client-facing InferResponse, tagging it with the serving replica_id for observability (the client can see which replica served each token).
Client disconnected mid-stream. Cancel the replica RPC to free up its resources (GPU memory, request slot).
Finish() retrieves the final status from the replica. A non-OK status means the replica encountered an error (crash, timeout, OOM, etc.). We return -1 to signal failure so the Infer retry loop can attempt failover to another replica.
Definition at line 399 of file gateway_server.cpp.
References LOG_WARN.
Referenced by Infer(), and InferHedged().
Member Data Documentation
port_
int llmgateway::GatewayServer::port_ private
Definition at line 85 of file gateway_server.h.
Referenced by GatewayServer(), port(), and Start().
registry_
ReplicaRegistry& llmgateway::GatewayServer::registry_ private
Definition at line 86 of file gateway_server.h.
Referenced by GatewayServer(), Infer(), and InferHedged().
lb_
LoadBalancer& llmgateway::GatewayServer::lb_ private
Definition at line 87 of file gateway_server.h.
Referenced by GatewayServer(), Infer(), and InferHedged().
cb_manager_
CircuitBreakerManager& llmgateway::GatewayServer::cb_manager_ private
Definition at line 88 of file gateway_server.h.
Referenced by GatewayServer(), Infer(), and InferHedged().
queue_
RequestQueue& llmgateway::GatewayServer::queue_ private
Definition at line 89 of file gateway_server.h.
Referenced by GatewayServer(), Infer(), and InferHedged().
server_
std::unique_ptr<grpc::Server> llmgateway::GatewayServer::server_ private
Definition at line 90 of file gateway_server.h.
Referenced by Start(), and Stop().
The documentation for this class was generated from the following files:
src/gateway/gateway_server.h
src/gateway/gateway_server.cpp