Distributed LLM Inference Gateway: llmgateway::LoadBalancer Class Reference
llmgateway::LoadBalancer Class Reference
#include <load_balancer.h>
Classes
struct Selection
Select a replica for the given prompt.
Public Member Functions
LoadBalancer (ReplicaRegistry &registry, int virtual_nodes=150)
std::optional< Selection > SelectReplica (const std::string &prompt, const std::unordered_set< std::string > &excluded={})
SelectReplica: the hot path called on every incoming inference request.
void RebuildRing ()
Rebuild the consistent hash ring from the current alive replicas.
Private Member Functions
std::optional< Selection > SelectByConsistentHash (const std::string &prompt, const std::unordered_set< std::string > &excluded)
Tier 1: consistent-hash walk.
std::optional< Selection > SelectByLeastConnections (const std::unordered_set< std::string > &excluded)
Tier 2: weighted least-connections fallback.
size_t Hash (const std::string &key) const
Hash function for the consistent hash ring.
Private Attributes
ReplicaRegistry & registry_
int virtual_nodes_
std::mutex ring_mutex_
Consistent hash ring: sorted map of hash -> replica_id.
std::map< size_t, std::string > ring_
Detailed Description
LoadBalancer: two-tier routing strategy for inference requests.
Tier 1 – Consistent Hashing (prompt-prefix affinity): Hash the first 64 characters of the prompt to a point on a ring. Walk clockwise until a replica with available capacity is found. If the prompt prefix matches a previous request, the same replica is selected. Virtual nodes spread load evenly.
Tier 2 – Weighted Least-Connections (capacity-aware fallback): If every replica on the hash ring is at capacity (or the ring is empty during startup), fall back to choosing the replica with the lowest score = active_requests / weight. This prevents overload and works without any prompt-specific state.
The consistent hash ring uses virtual_nodes_ points per replica (default 150) to minimize key redistribution when replicas join/leave. The ring is rebuilt on membership changes (triggered by gossip events),
not on every request, so SelectReplica is a fast lookup.
Definition at line 37 of file load_balancer.h.
Constructor & Destructor Documentation
LoadBalancer()
llmgateway::LoadBalancer::LoadBalancer (ReplicaRegistry & registry, int virtual_nodes = 150) explicit
Definition at line 17 of file load_balancer.cpp.
References registry_, and virtual_nodes_.
Member Function Documentation
SelectReplica()
std::optional< LoadBalancer::Selection > llmgateway::LoadBalancer::SelectReplica (const std::string & prompt, const std::unordered_set< std::string > & excluded = {})
SelectReplica: the hot path called on every incoming inference request.
It tries Tier 1 first (consistent hash for cache affinity) and only falls through to Tier 2 (least-connections) if the ring is empty or every ring position is at capacity.
Tier 1: try consistent hashing for prompt-prefix affinity.
Tier 2: fall back to weighted least-connections.
Definition at line 24 of file load_balancer.cpp.
References SelectByConsistentHash(), and SelectByLeastConnections().
RebuildRing()
void llmgateway::LoadBalancer::RebuildRing ()
Rebuild the consistent hash ring from the current alive replicas.
Should be called whenever membership changes (e.g., from a gossip callback). Acquires ring_mutex_ internally; safe to call concurrently with SelectReplica.
RebuildRing: reconstruct the hash ring from the current alive replica set.
Called on membership changes (replica join, leave, or state transition). We snapshot the alive replicas first (shared lock on the registry), then take the ring mutex to swap in the new ring. This two-step approach avoids holding both locks simultaneously.
Virtual nodes: each physical replica is placed at virtual_nodes_ positions on the ring using hash(replica_id + "#" + i). This ensures that when a single replica leaves, only ~1/N of the key space is remapped (consistent hashing property), and the load is spread evenly rather than clumped
around a few hash positions.
Definition at line 50 of file load_balancer.cpp.
References Hash(), LOG_DEBUG, registry_, ring_, ring_mutex_, and virtual_nodes_.
Referenced by main().
SelectByConsistentHash()
std::optional< LoadBalancer::Selection > llmgateway::LoadBalancer::SelectByConsistentHash (const std::string & prompt, const std::unordered_set< std::string > & excluded) private
Tier 1: consistent-hash walk.
Hash the prompt's first 64 chars to a point on the ring, then walk clockwise until a replica is found that is ALIVE/SUSPECT, not draining, not in excluded, and has capacity. Returns nullopt if the walk completes a full lap without finding a match, in which case the caller falls through to Tier 2.
Tier 1: Consistent hashing with clockwise walk.
Hash the prompt prefix (first 64 chars). Using only the prefix means requests that share a common prefix (e.g., system prompt + few-shot examples) will hash to the same ring position, giving stable prefix affinity.
lower_bound(h) finds the first ring point >= h (clockwise from h). If we overshoot the end, wrap to ring_.begin() (the ring is circular).
Walk clockwise, checking each candidate replica for:
not draining (rolling update in progress)
not DEAD (gossip has confirmed failure)
has capacity: max_capacity == 0 means unlimited (the replica self-manages concurrency), otherwise active_requests < max_capacity The first replica satisfying all three is returned.
If the walk completes a full loop without finding capacity, return
nullopt so the caller falls through to Tier 2.
Hash the prompt prefix (first 64 chars or the whole prompt if shorter).
Find the first ring position >= h (clockwise walk).
Walk the ring until we find a replica with capacity.
Skip replicas the caller has asked us to exclude (e.g., circuits open, just-failed stream). The next ring point may be a different replica; if not, we'll walk past it on the next iteration.
max_capacity == 0 means "unlimited": the replica has no gateway-enforced concurrency cap and self-manages its own parallelism.
Move clockwise.
Full loop – no capacity anywhere on the ring.
Definition at line 89 of file load_balancer.cpp.
References Hash(), registry_, ring_, and ring_mutex_.
Referenced by SelectReplica().
SelectByLeastConnections()
std::optional< LoadBalancer::Selection > llmgateway::LoadBalancer::SelectByLeastConnections (const std::unordered_set< std::string > & excluded) private
Tier 2: weighted least-connections fallback.
Scores each eligible replica as active_requests / weight and picks the minimum; uses reservoir sampling to break ties uniformly at random. Returns nullopt only when every alive replica is at capacity (the gateway then returns RESOURCE_EXHAUSTED).
Tier 2: Weighted least-connections.
Scoring: score(r) = active_requests(r) / weight(r). Dividing by weight means a replica with weight=2.0 can handle twice the load of a weight=1.0 replica before its score equals theirs. This naturally favors higher-capacity replicas (e.g., GPU vs CPU).
Capacity check: replicas at max_capacity are skipped entirely. max_capacity == 0 is treated as "unlimited" (same as in Tier 1).
Tiebreak: when multiple replicas have the same minimum score, we use reservoir sampling (Vitter's Algorithm R) to select uniformly at random among them in a single pass. This avoids the need to collect all tied candidates into a separate list. The k-th tied candidate replaces the current best with probability 1/k, which yields uniform selection.
Returns nullopt only when every alive replica is at capacity – the
caller (Infer) will then return RESOURCE_EXHAUSTED to the client.
Skip replicas that are at capacity (max_capacity > 0 means enforced).
Reservoir sampling: the k-th tied candidate replaces the current winner with probability 1/k, guaranteeing uniform random selection across all tied candidates.
Definition at line 159 of file load_balancer.cpp.
References llmgateway::g_rng, and registry_.
Referenced by SelectReplica().
Hash()
size_t llmgateway::LoadBalancer::Hash (const std::string & key) const private
Hash function for the consistent hash ring.
Uses std::hash<string> – fast and sufficient for load distribution (cryptographic strength is not needed here).
Definition at line 198 of file load_balancer.cpp.
Referenced by RebuildRing(), and SelectByConsistentHash().
Member Data Documentation
registry_
ReplicaRegistry& llmgateway::LoadBalancer::registry_ private
Definition at line 91 of file load_balancer.h.
Referenced by LoadBalancer(), RebuildRing(), SelectByConsistentHash(), and SelectByLeastConnections().
virtual_nodes_
int llmgateway::LoadBalancer::virtual_nodes_ private
Definition at line 92 of file load_balancer.h.
Referenced by LoadBalancer(), and RebuildRing().
ring_mutex_
std::mutex llmgateway::LoadBalancer::ring_mutex_ private
Consistent hash ring: sorted map of hash -> replica_id.
The std::map gives us O(log N) lower_bound for clockwise lookup. Protected by its own mutex (ring rebuild is infrequent, and the mutex scope does not overlap with the registry's shared_mutex).
Definition at line 98 of file load_balancer.h.
Referenced by RebuildRing(), and SelectByConsistentHash().
ring_
std::map<size_t, std::string> llmgateway::LoadBalancer::ring_ private
Definition at line 99 of file load_balancer.h.
Referenced by RebuildRing(), and SelectByConsistentHash().
The documentation for this class was generated from the following files:
src/gateway/load_balancer.h
src/gateway/load_balancer.cpp