Distributed LLM Inference Gateway: llmgateway::CircuitBreakerManager Class Reference
llmgateway::CircuitBreakerManager Class Reference
#include <circuit_breaker.h>
Public Member Functions
CircuitBreakerManager ()
============================================================================ CircuitBreakerManager: per-replica breaker lookup with lazy initialization.
CircuitBreakerManager (CircuitBreaker::Config config)
bool AllowRequest (const std::string &replica_id)
void RecordSuccess (const std::string &replica_id)
void RecordFailure (const std::string &replica_id)
CircuitBreaker::State GetState (const std::string &replica_id)
Private Member Functions
CircuitBreaker & GetOrCreate (const std::string &replica_id)
Returns a reference to the breaker for replica_id, creating one with the shared config_ if it does not yet exist.
Private Attributes
CircuitBreaker::Config config_
std::mutex mutex_
std::unordered_map< std::string, CircuitBreaker > breakers_
Detailed Description
CircuitBreakerManager: facade that maps replica_id -> CircuitBreaker.
Circuit breakers are created lazily on first access (GetOrCreate). All share the same Config, but each tracks its own sliding window and state independently. The manager's mutex protects the map structure (insert/lookup), while each CircuitBreaker has its own internal mutex for state transitions. This means checking/recording for different
replicas does not contend.
Definition at line 106 of file circuit_breaker.h.
Constructor & Destructor Documentation
CircuitBreakerManager() [1/2]
llmgateway::CircuitBreakerManager::CircuitBreakerManager ()
============================================================================ CircuitBreakerManager: per-replica breaker lookup with lazy initialization.
The manager mutex is held for the duration of each public method call. This is acceptable because the critical section is short (map lookup + delegation to the individual CircuitBreaker, which also holds its own mutex briefly). For higher concurrency, the manager mutex could be replaced with a concurrent map, but at the expected replica count
(tens, not thousands) this is not a bottleneck.
Definition at line 162 of file circuit_breaker.cpp.
References config_.
CircuitBreakerManager() [2/2]
llmgateway::CircuitBreakerManager::CircuitBreakerManager (CircuitBreaker::Config config) explicit
Definition at line 163 of file circuit_breaker.cpp.
References config_.
Member Function Documentation
AllowRequest()
bool llmgateway::CircuitBreakerManager::AllowRequest (const std::string & replica_id)
Definition at line 166 of file circuit_breaker.cpp.
References llmgateway::CircuitBreaker::AllowRequest(), GetOrCreate(), and mutex_.
RecordSuccess()
void llmgateway::CircuitBreakerManager::RecordSuccess (const std::string & replica_id)
Definition at line 171 of file circuit_breaker.cpp.
References GetOrCreate(), mutex_, and llmgateway::CircuitBreaker::RecordSuccess().
RecordFailure()
void llmgateway::CircuitBreakerManager::RecordFailure (const std::string & replica_id)
Definition at line 176 of file circuit_breaker.cpp.
References GetOrCreate(), mutex_, and llmgateway::CircuitBreaker::RecordFailure().
GetState()
CircuitBreaker::State llmgateway::CircuitBreakerManager::GetState (const std::string & replica_id)
Definition at line 181 of file circuit_breaker.cpp.
References GetOrCreate(), mutex_, and llmgateway::CircuitBreaker::state().
GetOrCreate()
CircuitBreaker & llmgateway::CircuitBreakerManager::GetOrCreate (const std::string & replica_id) private
Returns a reference to the breaker for replica_id, creating one with the shared config_ if it does not yet exist.
GetOrCreate: lazy factory.
A breaker is created on first access with the shared Config. This means newly discovered replicas (via gossip) get a circuit breaker automatically on their first routed request, with no explicit registration step required.
Definition at line 191 of file circuit_breaker.cpp.
References breakers_, and config_.
Referenced by AllowRequest(), GetState(), RecordFailure(), and RecordSuccess().
Member Data Documentation
config_
CircuitBreaker::Config llmgateway::CircuitBreakerManager::config_ private
Definition at line 118 of file circuit_breaker.h.
Referenced by CircuitBreakerManager(), CircuitBreakerManager(), and GetOrCreate().
mutex_
std::mutex llmgateway::CircuitBreakerManager::mutex_ private
Definition at line 119 of file circuit_breaker.h.
Referenced by AllowRequest(), GetState(), RecordFailure(), and RecordSuccess().
breakers_
std::unordered_map<std::string, CircuitBreaker> llmgateway::CircuitBreakerManager::breakers_ private
Definition at line 120 of file circuit_breaker.h.
Referenced by GetOrCreate().
The documentation for this class was generated from the following files:
src/gateway/circuit_breaker.h
src/gateway/circuit_breaker.cpp