Distributed LLM Inference Gateway: llmgateway::gossip::SwimProtocol Class Reference
llmgateway::gossip::SwimProtocol Class Reference
#include <swim.h>
Public Member Functions
SwimProtocol (const std::string &my_id, const std::string &my_address, uint16_t udp_port, SwimConfig config={})
~SwimProtocol ()
SwimProtocol (const SwimProtocol &)=delete
Non-copyable.
SwimProtocol & operator= (const SwimProtocol &)=delete
void Start ()
Start the protocol (launches sender + receiver threads).
void Stop ()
Stop the protocol (signals threads and joins).
void LeaveCluster ()
Graceful leave: broadcast a DEAD message about ourselves to all peers so they can remove us instantly (no need to wait for suspect timeout).
void JoinCluster (const std::vector< std::string > &seed_addresses)
Bootstrap by adding seed nodes to the membership list.
void SetMembershipCallback (MembershipCallback callback)
Set callback for membership changes (thread-safe, forwarded to MembershipList).
MembershipList & membership_list ()
Access the membership list (for gateway to query alive replicas).
const MembershipList & membership_list () const
void SetMyLoad (int32_t active_requests, int32_t max_capacity, const std::string &model_version)
Update my own load metadata (piggybacked on gossip messages).
bool is_running () const
Private Member Functions
void SenderLoop ()
Thread entry points.
void ReceiverLoop ()
============================================================================ Receiver thread
void DoPingRound ()
Run one SWIM probe cycle: pick a random alive peer, send PING, wait for ACK up to ping_timeout_ms.
void HandleMessage (const GossipMessage &msg, const Address &sender_addr)
Top-level inbound dispatch.
void HandlePing (const GossipMessage &msg, const Address &sender_addr)
Reply to a direct PING with an ACK (same seq_num), carrying our own piggyback updates.
void HandlePingReq (const GossipMessage &msg, const Address &sender_addr)
Received a PING_REQ to indirectly probe target_id: forward a PING to the target and, on ACK, relay an ACK back to the original requester.
void HandleAck (const GossipMessage &msg)
Match the ACK's seq_num against pending_acks_ and signal the waiting thread (which is blocked in WaitForAck).
void ProcessPiggybackedUpdates (const GossipMessage &msg)
Apply every MembershipUpdate piggybacked on a message to the local membership list, fire the self-refutation check for each, and let MembershipList's conflict-resolution rules decide which updates actually take effect.
void CheckSuspectTimeouts ()
Promote members whose SUSPECT timer has exceeded suspect_timeout_ms to DEAD.
void SendMessage (const Address &dest, MessageType type, const std::string &target_id, uint64_t seq_num)
Build a GossipMessage of the given type, attach up to max_piggyback_updates pending updates, and send it to dest.
bool WaitForAck (uint64_t seq_num, int timeout_ms)
Block up to timeout_ms for an ACK with the given seq_num to arrive (via the receiver thread calling RecordAck).
void RecordAck (uint64_t seq_num)
Mark the given seq_num as received and wake any thread waiting in WaitForAck.
void CheckSelfRefutation (const MembershipUpdate &update)
If an incoming update declares us SUSPECT or DEAD at our current incarnation, bump our incarnation and broadcast ALIVE so peers override the stale rumor.
Private Attributes
std::string my_id_
std::string my_address_
SwimConfig config_
UdpTransport transport_
MembershipList membership_list_
std::atomic< bool > running_ {false}
std::thread sender_thread_
std::thread receiver_thread_
std::mutex ack_mutex_
Pending ACKs: sender waits, receiver notifies.
std::condition_variable ack_cv_
std::unordered_map< uint64_t, bool > pending_acks_
std::atomic< uint64_t > next_seq_num_ {1}
Sequence number counter (atomic, monotonically increasing).
std::mutex load_mutex_
My load metadata (updated by the replica/gateway, piggybacked on messages).
int32_t my_active_requests_ = 0
int32_t my_max_capacity_ = 0
std::string my_model_version_
Detailed Description
SwimProtocol: SWIM-style gossip-based failure detector and membership protocol (Das, Gupta, Motivala; "SWIM", DSN 2002).
Each node runs two threads:
Sender loop: every T_protocol, pings a random peer, and if the direct ping times out, asks k=indirect_ping_count other peers to relay a ping. This indirect probing separates real failures from transient network drops. Also scans for SUSPECT members whose timers have expired and marks them DEAD.
Receiver loop: handles inbound PING, PING_REQ, and ACK messages from peers, and also processes piggybacked membership updates that ride on every outgoing packet.
State propagation is fully decentralized. When a node learns of a state change (locally observed or received from a peer), the update is queued in the MembershipList's piggyback buffer and attached to subsequent outgoing messages until it has been sent kMaxPiggybackSends times or the buffer fills. No heartbeats, no central health monitor.
Self-refutation: if a node sees a piggybacked update marking itself SUSPECT/DEAD, it increments its own incarnation number and broadcasts an ALIVE update at the new incarnation. Because the conflict-resolution rules in MembershipList prefer the higher incarnation, the stale rumor is quickly overridden.
Thread-safety:
Start()/Stop() are not thread-safe; call once.
SetMembershipCallback, SetMyLoad, membership_list() accessors, and is_running() are safe to call at any time from any thread.
The sender and receiver threads synchronize only via the MembershipList (which has its own shared_mutex) and a small ACK
tracking table guarded by ack_mutex_.
Definition at line 67 of file swim.h.
Constructor & Destructor Documentation
SwimProtocol() [1/2]
llmgateway::gossip::SwimProtocol::SwimProtocol (const std::string & my_id, const std::string & my_address, uint16_t udp_port, SwimConfig config = {})
Definition at line 37 of file swim.cpp.
References config_, membership_list_, my_address_, my_id_, and transport_.
Referenced by operator=(), and SwimProtocol().
~SwimProtocol()
llmgateway::gossip::SwimProtocol::~SwimProtocol ()
Definition at line 48 of file swim.cpp.
References Stop().
SwimProtocol() [2/2]
llmgateway::gossip::SwimProtocol::SwimProtocol (const SwimProtocol &) delete
Non-copyable.
References SwimProtocol().
Member Function Documentation
operator=()
SwimProtocol & llmgateway::gossip::SwimProtocol::operator= (const SwimProtocol &) delete
References SwimProtocol().
Start()
void llmgateway::gossip::SwimProtocol::Start ()
Start the protocol (launches sender + receiver threads).
Receiver must start before sender so incoming ACKs aren't missed.
Definition at line 52 of file swim.cpp.
References LOG_INFO, my_id_, receiver_thread_, ReceiverLoop(), running_, sender_thread_, SenderLoop(), and transport_.
Referenced by main().
Stop()
void llmgateway::gossip::SwimProtocol::Stop ()
Stop the protocol (signals threads and joins).
Definition at line 63 of file swim.cpp.
References LOG_INFO, my_id_, receiver_thread_, running_, and sender_thread_.
Referenced by main(), and ~SwimProtocol().
LeaveCluster()
void llmgateway::gossip::SwimProtocol::LeaveCluster ()
Graceful leave: broadcast a DEAD message about ourselves to all peers so they can remove us instantly (no need to wait for suspect timeout).
Graceful leave: broadcast a DEAD message about ourselves so peers can remove us instantly without waiting for the suspect timeout.
Call this before Stop() during rolling updates for faster transitions.
This is an optimization for rolling updates — drain → graceful leave → restart is significantly faster than drain → crash detection → restart.
Use incarnation + 1 to ensure this overrides any concurrent ALIVE messages that might be in-flight from our own piggybacked updates.
Definition at line 77 of file swim.cpp.
References LOG_INFO, membership_list_, my_address_, my_id_, next_seq_num_, llmgateway::gossip::ParseAddress(), and transport_.
JoinCluster()
void llmgateway::gossip::SwimProtocol::JoinCluster (const std::vector< std::string > & seed_addresses)
Bootstrap by adding seed nodes to the membership list.
Bootstrap: add seed nodes so the first protocol round has peers to ping.
Seeds are added with a temporary "seed-<addr>" ID. The real ID is learned when the seed responds and its sender_id is extracted from the PING/ACK.
Definition at line 105 of file swim.cpp.
References membership_list_, and my_address_.
Referenced by main().
SetMembershipCallback()
void llmgateway::gossip::SwimProtocol::SetMembershipCallback (MembershipCallback callback)
Set callback for membership changes (thread-safe, forwarded to MembershipList).
Definition at line 113 of file swim.cpp.
References membership_list_.
Referenced by main().
membership_list() [1/2]
MembershipList & llmgateway::gossip::SwimProtocol::membership_list () inline
Access the membership list (for gateway to query alive replicas).
Definition at line 95 of file swim.h.
References membership_list_.
Referenced by main().
membership_list() [2/2]
const MembershipList & llmgateway::gossip::SwimProtocol::membership_list () const inline
Definition at line 96 of file swim.h.
References membership_list_.
SetMyLoad()
void llmgateway::gossip::SwimProtocol::SetMyLoad (int32_t active_requests, int32_t max_capacity, const std::string & model_version)
Update my own load metadata (piggybacked on gossip messages).
Publish load metadata that will be piggybacked on outgoing gossip messages.
The gateway reads this to make load-aware routing decisions.
Definition at line 119 of file swim.cpp.
References load_mutex_, my_active_requests_, my_max_capacity_, and my_model_version_.
Referenced by main().
is_running()
bool llmgateway::gossip::SwimProtocol::is_running () const inline
Definition at line 102 of file swim.h.
References running_.
Referenced by main().
SenderLoop()
void llmgateway::gossip::SwimProtocol::SenderLoop () private
Thread entry points.
============================================================================ Sender thread
SenderLoop wakes every protocol_period_ms, runs DoPingRound, and checks suspect timers. ReceiverLoop blocks on UDP recv and dispatches inbound messages to the Handle* methods.
Runs one "protocol round" every T_protocol milliseconds. Each round:
Pings a random peer (direct probe)
If no ACK, tries indirect probes through k other peers
If still no ACK, marks the peer as SUSPECT
4. Scans suspect list and promotes timed-out suspects to DEAD
Maintain consistent round timing by sleeping for the remainder. If the round took longer than T_protocol (e.g., due to slow indirect probes), the next round starts immediately with no sleep.
Definition at line 137 of file swim.cpp.
References CheckSuspectTimeouts(), config_, DoPingRound(), and running_.
Referenced by Start().
ReceiverLoop()
void llmgateway::gossip::SwimProtocol::ReceiverLoop () private
============================================================================ Receiver thread
Listens for incoming UDP messages and dispatches to the appropriate handler.
Runs continuously with a 100ms receive timeout to allow clean shutdown.
Definition at line 264 of file swim.cpp.
References HandleMessage(), running_, and transport_.
Referenced by Start().
DoPingRound()
void llmgateway::gossip::SwimProtocol::DoPingRound () private
Run one SWIM probe cycle: pick a random alive peer, send PING, wait for ACK up to ping_timeout_ms.
On timeout, fan out PING_REQ to k other peers; if none of them can reach the target either, mark the target SUSPECT.
Step 1: Select a random alive peer to probe.
Register the pending ACK before sending, so the receiver thread can record it even if the response arrives very quickly.
Step 2: Send direct PING.
Step 3: Wait for direct ACK.
Step 4: Direct ping failed — try indirect probes. Ask k random other alive peers to ping the suspect on our behalf. This handles cases where the direct network path is temporarily broken but the suspect is reachable through other nodes.
Step 5: Wait for any indirect ACK (any one is enough to confirm alive).
Step 6: Both direct and indirect probes failed — mark SUSPECT. The peer gets T_suspect to refute (via incarnation increment) before being declared DEAD.
Definition at line 155 of file swim.cpp.
References ack_cv_, ack_mutex_, config_, membership_list_, next_seq_num_, llmgateway::gossip::ParseAddress(), pending_acks_, SendMessage(), and WaitForAck().
Referenced by SenderLoop().
HandleMessage()
void llmgateway::gossip::SwimProtocol::HandleMessage (const GossipMessage & msg, const Address & sender_addr) private
Top-level inbound dispatch.
Processes any piggybacked membership updates first (so Handle* methods see the latest state), then routes to the per-type handler.
Always process piggybacked membership updates first, regardless of message type. This is how SWIM achieves epidemic dissemination — every message carries state updates as a "free" side channel.
Definition at line 274 of file swim.cpp.
References HandleAck(), HandlePing(), HandlePingReq(), and ProcessPiggybackedUpdates().
Referenced by ReceiverLoop().
HandlePing()
void llmgateway::gossip::SwimProtocol::HandlePing (const GossipMessage & msg, const Address & sender_addr) private
Reply to a direct PING with an ACK (same seq_num), carrying our own piggyback updates.
PING handler: learn the sender's identity and reply with ACK.
The sender's real ID is extracted from the message, replacing any temporary "seed-<addr>" ID we may have assigned during bootstrap.
Definition at line 299 of file swim.cpp.
References membership_list_, SendMessage(), and llmgateway::gossip::Address::ToString().
Referenced by HandleMessage().
HandlePingReq()
void llmgateway::gossip::SwimProtocol::HandlePingReq (const GossipMessage & msg, const Address & sender_addr) private
Received a PING_REQ to indirectly probe target_id: forward a PING to the target and, on ACK, relay an ACK back to the original requester.
PING_REQ handler: we are acting as a proxy for indirect probing.
Forward a PING to the target, and if we get an ACK, relay it back to the original requester. This enables failure detection even when the direct path between the requester and target is broken.
Target is alive — relay ACK back to the original requester using their original sequence number so they can match it.
Definition at line 311 of file swim.cpp.
References ack_mutex_, config_, membership_list_, next_seq_num_, llmgateway::gossip::ParseAddress(), pending_acks_, SendMessage(), and WaitForAck().
Referenced by HandleMessage().
HandleAck()
void llmgateway::gossip::SwimProtocol::HandleAck (const GossipMessage & msg) private
Match the ACK's seq_num against pending_acks_ and signal the waiting thread (which is blocked in WaitForAck).
Definition at line 336 of file swim.cpp.
References RecordAck().
Referenced by HandleMessage().
ProcessPiggybackedUpdates()
void llmgateway::gossip::SwimProtocol::ProcessPiggybackedUpdates (const GossipMessage & msg) private
Apply every MembershipUpdate piggybacked on a message to the local membership list, fire the self-refutation check for each, and let MembershipList's conflict-resolution rules decide which updates actually take effect.
Process piggybacked membership updates from an incoming message.
Before applying each update, check if it's a suspicion about ourselves that needs to be refuted.
Definition at line 343 of file swim.cpp.
References CheckSelfRefutation(), and membership_list_.
Referenced by HandleMessage().
CheckSuspectTimeouts()
void llmgateway::gossip::SwimProtocol::CheckSuspectTimeouts () private
Promote members whose SUSPECT timer has exceeded suspect_timeout_ms to DEAD.
Scan the suspect list and promote any member that has been SUSPECT for longer than T_suspect to DEAD.
Called once per protocol period by the sender loop.
This runs once per protocol round.
Definition at line 244 of file swim.cpp.
References config_, and membership_list_.
Referenced by SenderLoop().
SendMessage()
void llmgateway::gossip::SwimProtocol::SendMessage (const Address & dest, MessageType type, const std::string & target_id, uint64_t seq_num) private
Build a GossipMessage of the given type, attach up to max_piggyback_updates pending updates, and send it to dest.
============================================================================ Message sending
Returns after the UDP send completes; acks (if any) are awaited separately.
Every outgoing message carries two types of piggybacked data:
Recent membership updates from the piggyback buffer (epidemic dissemination)
Our own load metadata (active_requests, max_capacity, model_version)
This means every PING, ACK, and PING_REQ doubles as a gossip vector,
spreading membership and load information without dedicated gossip rounds.
Attach recent membership updates for epidemic dissemination.
Attach our own load metadata so the gateway can make routing decisions based on each replica's self-reported load.
Definition at line 384 of file swim.cpp.
References config_, load_mutex_, membership_list_, my_active_requests_, my_address_, my_id_, my_max_capacity_, my_model_version_, and transport_.
Referenced by DoPingRound(), HandlePing(), and HandlePingReq().
WaitForAck()
bool llmgateway::gossip::SwimProtocol::WaitForAck (uint64_t seq_num, int timeout_ms) private
Block up to timeout_ms for an ACK with the given seq_num to arrive (via the receiver thread calling RecordAck).
============================================================================ ACK coordination between sender and receiver threads
Returns true if the ACK was received, false on timeout.
The sender registers a pending ACK (seq_num → false), sends a message, then calls WaitForAck which blocks on a condition_variable. The receiver calls RecordAck when an ACK arrives, setting the flag to
true and notifying the condition_variable.
Definition at line 425 of file swim.cpp.
References ack_cv_, ack_mutex_, and pending_acks_.
Referenced by DoPingRound(), and HandlePingReq().
RecordAck()
void llmgateway::gossip::SwimProtocol::RecordAck (uint64_t seq_num) private
Mark the given seq_num as received and wake any thread waiting in WaitForAck.
Definition at line 435 of file swim.cpp.
References ack_cv_, ack_mutex_, and pending_acks_.
Referenced by HandleAck().
CheckSelfRefutation()
void llmgateway::gossip::SwimProtocol::CheckSelfRefutation (const MembershipUpdate & update) private
If an incoming update declares us SUSPECT or DEAD at our current incarnation, bump our incarnation and broadcast ALIVE so peers override the stale rumor.
Self-refutation: if another node thinks we are SUSPECT or DEAD, increment our incarnation number to override the false suspicion.
The incremented incarnation will be piggybacked on our next outgoing message, propagating the refutation through the cluster.
This is the key mechanism that prevents false positives in SWIM: a slow-but-alive node can always clear its own suspicion by proving it's still running (via a higher incarnation number).
Definition at line 358 of file swim.cpp.
References LOG_INFO, membership_list_, and my_id_.
Referenced by ProcessPiggybackedUpdates().
Member Data Documentation
my_id_
std::string llmgateway::gossip::SwimProtocol::my_id_ private
Definition at line 166 of file swim.h.
Referenced by CheckSelfRefutation(), LeaveCluster(), SendMessage(), Start(), Stop(), and SwimProtocol().
my_address_
std::string llmgateway::gossip::SwimProtocol::my_address_ private
Definition at line 167 of file swim.h.
Referenced by JoinCluster(), LeaveCluster(), SendMessage(), and SwimProtocol().
config_
SwimConfig llmgateway::gossip::SwimProtocol::config_ private
Definition at line 168 of file swim.h.
Referenced by CheckSuspectTimeouts(), DoPingRound(), HandlePingReq(), SenderLoop(), SendMessage(), and SwimProtocol().
transport_
UdpTransport llmgateway::gossip::SwimProtocol::transport_ private
Definition at line 170 of file swim.h.
Referenced by LeaveCluster(), ReceiverLoop(), SendMessage(), Start(), and SwimProtocol().
membership_list_
MembershipList llmgateway::gossip::SwimProtocol::membership_list_ private
Definition at line 171 of file swim.h.
Referenced by CheckSelfRefutation(), CheckSuspectTimeouts(), DoPingRound(), HandlePing(), HandlePingReq(), JoinCluster(), LeaveCluster(), membership_list(), membership_list(), ProcessPiggybackedUpdates(), SendMessage(), SetMembershipCallback(), and SwimProtocol().
running_
std::atomic<bool> llmgateway::gossip::SwimProtocol::running_ {false} private
Definition at line 173 of file swim.h.
Referenced by is_running(), ReceiverLoop(), SenderLoop(), Start(), and Stop().
sender_thread_
std::thread llmgateway::gossip::SwimProtocol::sender_thread_ private
Definition at line 174 of file swim.h.
Referenced by Start(), and Stop().
receiver_thread_
std::thread llmgateway::gossip::SwimProtocol::receiver_thread_ private
Definition at line 175 of file swim.h.
Referenced by Start(), and Stop().
ack_mutex_
std::mutex llmgateway::gossip::SwimProtocol::ack_mutex_ private
Pending ACKs: sender waits, receiver notifies.
Definition at line 178 of file swim.h.
Referenced by DoPingRound(), HandlePingReq(), RecordAck(), and WaitForAck().
ack_cv_
std::condition_variable llmgateway::gossip::SwimProtocol::ack_cv_ private
Definition at line 179 of file swim.h.
Referenced by DoPingRound(), RecordAck(), and WaitForAck().
pending_acks_
std::unordered_map<uint64_t, bool> llmgateway::gossip::SwimProtocol::pending_acks_ private
Definition at line 180 of file swim.h.
Referenced by DoPingRound(), HandlePingReq(), RecordAck(), and WaitForAck().
next_seq_num_
std::atomic<uint64_t> llmgateway::gossip::SwimProtocol::next_seq_num_ {1} private
Sequence number counter (atomic, monotonically increasing).
Definition at line 183 of file swim.h.
Referenced by DoPingRound(), HandlePingReq(), and LeaveCluster().
load_mutex_
std::mutex llmgateway::gossip::SwimProtocol::load_mutex_ private
My load metadata (updated by the replica/gateway, piggybacked on messages).
Definition at line 186 of file swim.h.
Referenced by SendMessage(), and SetMyLoad().
my_active_requests_
int32_t llmgateway::gossip::SwimProtocol::my_active_requests_ = 0 private
Definition at line 187 of file swim.h.
Referenced by SendMessage(), and SetMyLoad().
my_max_capacity_
int32_t llmgateway::gossip::SwimProtocol::my_max_capacity_ = 0 private
Definition at line 188 of file swim.h.
Referenced by SendMessage(), and SetMyLoad().
my_model_version_
std::string llmgateway::gossip::SwimProtocol::my_model_version_ private
Definition at line 189 of file swim.h.
Referenced by SendMessage(), and SetMyLoad().
The documentation for this class was generated from the following files:
src/gossip/swim.h
src/gossip/swim.cpp