Distributed LLM Inference Gateway: llmgateway::gossip Namespace Reference
llmgateway::gossip Namespace Reference
Thread-safe membership table used by the SWIM protocol.
Classes
struct Address
Parsed network address used throughout the gossip layer.
struct MemberInfo
class MembershipList
Thread-safe membership list with SWIM incarnation-based conflict resolution.
struct SwimConfig
Tuning parameters for the SWIM failure detector.
class SwimProtocol
class UdpTransport
Typedefs
using MembershipCallback
Callback invoked when membership changes.
Functions
Address ParseAddress (const std::string &addr_str)
Parse a "host:port" string into an Address.
Variables
static thread_local std::mt19937 g_rng {std::random_device{}()}
Thread-local random engine for peer selection.
static thread_local std::mt19937 g_rng {std::random_device{}()}
static constexpr size_t kMaxDatagram = 4096
Max UDP datagram size for gossip messages.
Detailed Description
Thread-safe membership table used by the SWIM protocol.
UDP transport layer for the SWIM gossip protocol.
SWIM gossip protocol: decentralized membership and failure detection.
SWIM protocol implementation.
Stores per-member state and incarnation, resolves conflicting updates, and maintains a piggyback buffer of recent changes to disseminate on outgoing gossip messages.
Reference: Das et al., "SWIM: Scalable Weakly-consistent Infection-style Process Group Membership Protocol", DSN 2002.
Architecture: Two threads — a sender (periodic PING loop) and a receiver (UDP listen loop). They communicate via a pending_acks map with condition_variable notification. The sender waits for ACKs; the receiver deposits them.
Failure detection pipeline (per protocol round):
Select random alive peer → send PING
If ACK received within T_ping → peer alive, done
If no ACK → select k random proxies → send PING_REQ (indirect probe)
If any proxy relays an ACK → peer alive, done
If no indirect ACK → mark peer SUSPECT
If peer stays SUSPECT for T_suspect → mark DEAD
If peer receives its own SUSPECT → increment incarnation → refute
Dissemination: Membership updates are piggybacked on every outgoing message (PING, ACK, PING_REQ). This provides O(log N) convergence without dedicated gossip rounds, using the protocol's existing message traffic as a carrier.
Every replica and the gateway runs one SwimProtocol instance. Together they converge on a consistent view of alive/suspect/dead members without any centralized health monitor.
Sends and receives length-prefixed protobuf datagrams over a single bound socket. See swim.h for the protocol that uses this transport.
Typedef Documentation
MembershipCallback
using llmgateway::gossip::MembershipCallback
Initial value:
    std::function<void(const std::string& member_id, MemberState old_state,
                       MemberState new_state)>
Callback invoked when membership changes.
Parameters: member_id, old_state, new_state
Definition at line 32 of file membership_list.h.
Function Documentation
ParseAddress()
Address llmgateway::gossip::ParseAddress (const std::string & addr_str)
Parse a "host:port" string into an Address.
Throws std::invalid_argument on malformed input (missing colon, non-numeric port, port out of range). IPv6 addresses are not supported — hostnames are treated as-is and resolved by the OS at send time.
Definition at line 19 of file udp_transport.cpp.
Referenced by llmgateway::gossip::SwimProtocol::DoPingRound(), llmgateway::gossip::SwimProtocol::HandlePingReq(), and llmgateway::gossip::SwimProtocol::LeaveCluster().
Variable Documentation
g_rng [1/2]
thread_local std::mt19937 llmgateway::gossip::g_rng {std::random_device{}()} static
Thread-local random engine for peer selection.
Definition at line 9 of file membership_list.cpp.
Referenced by llmgateway::gossip::MembershipList::GetRandomAlivePeer().
g_rng [2/2]
thread_local std::mt19937 llmgateway::gossip::g_rng {std::random_device{}()} static
Definition at line 35 of file swim.cpp.
kMaxDatagram
size_t llmgateway::gossip::kMaxDatagram = 4096 static constexpr
Max UDP datagram size for gossip messages.
SWIM messages with piggybacked updates should fit well within this.
Definition at line 17 of file udp_transport.cpp.
Referenced by llmgateway::gossip::UdpTransport::Receive(), and llmgateway::gossip::UdpTransport::Send().