Distributed LLM Inference Gateway: src/replica/main.cpp File Reference
main.cpp File Reference
#include <csignal>
#include <iostream>
#include <sstream>
#include <string>
#include <thread>
#include <vector>
#include "common/log.h"
#include "gossip/swim.h"
#include "replica/replica_server.h"
Functions
void signal_handler (int signal)
std::vector< std::string > ParseSeeds (const std::string &seeds_str)
int main (int argc, char *argv[])
Variables
static ReplicaServer * g_server = nullptr
static SwimProtocol * g_swim = nullptr
Function Documentation
signal_handler()
void signal_handler (int signal)
Definition at line 18 of file main.cpp.
References g_server, and g_swim.
ParseSeeds()
std::vector< std::string > ParseSeeds (const std::string & seeds_str)
Definition at line 23 of file main.cpp.
Referenced by main().
main()
int main (int argc, char * argv[])
Defaults
Default gossip port: gRPC port + 10000.
Start gRPC server.
Start gossip protocol.
Periodically update gossip with current load metadata.
Main loop: update load info in gossip every 500ms.
Definition at line 33 of file main.cpp.
References llmgateway::ReplicaServer::active_requests(), g_server, g_swim, llmgateway::gossip::SwimProtocol::is_running(), llmgateway::gossip::SwimProtocol::JoinCluster(), ParseSeeds(), llmgateway::ReplicaServer::set_error_rate(), llmgateway::ReplicaServer::set_model_version(), llmgateway::ReplicaServer::set_reject_all(), llmgateway::gossip::SwimProtocol::SetMyLoad(), signal_handler(), llmgateway::gossip::SwimProtocol::Start(), llmgateway::ReplicaServer::Start(), and llmgateway::ReplicaServer::Stop().
Variable Documentation
g_server
ReplicaServer* g_server = nullptr static
Definition at line 15 of file main.cpp.
g_swim
SwimProtocol* g_swim = nullptr static
Definition at line 16 of file main.cpp.
Referenced by main(), and signal_handler().